boot.o: boot.S multiboot.h x86_desc.h types.h
int_wrappers.o: int_wrappers.S
paging_help.o: paging_help.S
syscall_linkage.o: syscall_linkage.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c file_system.h x86_desc.h types.h lib.h \
  multiboot.h system_calls.h terminal.h rtc.h
i8259.o: i8259.c i8259.h types.h lib.h
int_handler.o: int_handler.c int_handler.h x86_desc.h types.h lib.h \
  int_wrapper.h keyboard.h rtc.h i8259.h syscall_linkage.h scheduling.h \
  system_calls.h file_system.h multiboot.h terminal.h paging.h debug.h \
  paging_help.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  int_handler.h int_wrapper.h keyboard.h rtc.h syscall_linkage.h \
  scheduling.h system_calls.h file_system.h terminal.h paging.h \
  paging_help.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h terminal.h \
  system_calls.h file_system.h x86_desc.h multiboot.h rtc.h scheduling.h \
  paging.h debug.h paging_help.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h system_calls.h \
  file_system.h x86_desc.h multiboot.h rtc.h
paging.o: paging.c paging.h x86_desc.h types.h lib.h i8259.h debug.h \
  paging_help.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
scheduling.o: scheduling.c scheduling.h lib.h types.h system_calls.h \
  file_system.h x86_desc.h multiboot.h terminal.h rtc.h paging.h i8259.h \
  debug.h paging_help.h syscall_linkage.h
system_calls.o: system_calls.c syscall_linkage.h types.h lib.h x86_desc.h \
  i8259.h system_calls.h file_system.h multiboot.h terminal.h rtc.h \
  paging.h debug.h paging_help.h scheduling.h
terminal.o: terminal.c terminal.h types.h lib.h keyboard.h system_calls.h \
  file_system.h x86_desc.h multiboot.h rtc.h paging.h i8259.h debug.h \
  paging_help.h
